# Generated by Django 5.0.6 on 2024-07-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_rename_acknowledgement_date_purchaseorder_acknowledgment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
