from django.urls import path,include
from rest_framework.routers import DefaultRouter
from vendors.views import VendorModelViewset
from purchase_order.views import PurchaseOrderViewSet
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

router = DefaultRouter()
router.register('vendors', VendorModelViewset, basename='vendor')
router.register('purchaseorders', PurchaseOrderViewSet, basename='purchase_order')

urlpatterns = [
    # Include the URLs generated by the router
    path('',include(router.urls)),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),  # Obtain token endpoint
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),  # Refresh token endpoint
]